### ISSUE TITLE
components.parameters.region.schema.enum does not contain 'en' which is the default value in openapi3 spec

### ISSUE THREAD

**Issue by WORMSS** [googlemaps/openapi-specification#197]
`components.parameters.region.schema.enum` does not contain 'en' which is the default value

located in the openapi3 spec

`/dist/google-maps-platform-openapi3.json`

Seems I can't link directly to the file for ease of use, because Github thinks the file is too big.

Should be around line 28303-28558

**Comment by jpoehnelt** [comment]
Thanks for catching this! I'll get a fix out right away. Do you mind sharing how you are using the Open API spec or the various outputs that lead you to this bug? Thanks again!

**Comment by WORMSS** [comment]
Ran it against `https://github.com/ferdikoomen/openapi-typescript-codegen` 
it tried to do `region = 'en'` but `'en'` was an invalid input

**Comment by jpoehnelt** [comment]
Got it. Any other issues with codegen? I'm looking to eventually generate and publish some libraries from this.

**Comment by WORMSS** [comment]
But.... I actually had to fix a bug in the repo, since their version couldn't handle the `~1` for path argument in references... so see https://github.com/ferdikoomen/openapi-typescript-codegen/issues/824 for my hack/fix

**Comment by jpoehnelt** [comment]
I could add a dereferenced (resolve all $ref) spec if that seems to be an issue with codegens.

**Comment by WORMSS** [comment]
Could do. I personally think the codegens should be able to deal with the spec correctly.. I've found others which can.. 

The only issue is that the naming of the endpoints were really bad.. Like.. REALLY bad.. after it got spit out of the codegen.

End endpoints ended up being like 
```ts
getPlacesApiService()
getPlacesApiService1()
getPlacesApiService2()
getPlacesApiService3()
getPlacesApiService4()
```
instead of something useful like
```ts
getPlacesTextSearch()
getPlacesDetails()
```
etc etc

I am unsure if that is an issue with the `openapi-typescript-codegen` or the spec file though. I would have to check that particular issue with other tools and see what they spit out.. 
Since you correctly tagged similar apis such as `places/roads/streetview`.. I know it handles our own api correctly, but I have not done a side by side to know 'how' these codegens decide the names of the functions

**Comment by jpoehnelt** [comment]
Seems I could improve that with `operationId` although the fallback in the could also be improved. https://github.com/ferdikoomen/openapi-typescript-codegen/blob/830b317d0a0f6aaa97dba43818ce6d1ccc109be2/src/openApi/v3/parser/getOperation.ts#L22-L23

**Comment by WORMSS** [comment]
It would seem you hit it perfectly.. 
our API has `"operationId": "Card_CardAccessAdvisorByRole",` and the function does seem to indicate this is what it would output if you remove non alphanumerics and run a run camelcase on it would result in `cardCardAccessAdvisorByUser` 
the `cardCard` in our codebase is a little undesirable, but nothing to cry too much about...

Good spot with `getOperation`
