### ISSUE TITLE
PlacesSearch/SearchNearby:: PlacePhoto - [bug]: Documentation error 

### ISSUE THREAD

**Issue by Mike-Tran** [googlemaps/openapi-specification#229]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
  - Done
2. OS type and version 
  - NA
3. Library version and other environment information
  - "Last updated 2021-09-29 UTC."

#### Steps to reproduce

  1. https://developers.google.com/maps/documentation/places/web-service/search-nearby
  2. Under PlacePhoto
  3. See how example API call contradicts the required parameters for the call

#### Code example

```
https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=photo_reference&key=YOUR_API_KEY
```

Field | Required | Type | Description
-- | -- | -- | --
height | required | number | The height of the photo.
html_attributions | required | Array<string> | The HTML attributions for the photo.
photo_reference | required | string | A string used to identify the photo when you perform a Photo request.
width | required | number | The width of the photo.

Following these steps will guarantee the quickest resolution possible.

Thanks!
<img width="894" alt="Screen Shot 2021-10-03 at 9 59 28 PM" src="https://user-images.githubusercontent.com/11032490/135796804-2b0ba6d7-da1e-421a-9602-f2f829160c84.png">

**Comment by jpoehnelt** [comment]
I don't quite follow with what is the issue here. 

* `width` is the dimension within the photo schema returned in an API request such as place details. 
* `maxwidth` is a parameter for a place photo API request

**Comment by Mike-Tran** [comment]
I apologize for the lack of clarification.

In the docs, it says that height, html_attributions, photo_reference, and width are required parameters for the API call. Maybe, I have misinterpreted the documentation as saying those are the required return values from the API.

**Comment by jpoehnelt** [comment]
Yeah, those properties are part of the response schema for the other place apis.

![Screen Shot 2021-10-04 at 10 47 06 AM](https://user-images.githubusercontent.com/3392975/135891299-c12d5b49-06fb-4134-be38-f443924798d9.png)

**Comment by Mike-Tran** [comment]
I apologize for misinterpreting the docs. Ill go ahead and close out the issue.
