### ISSUE TITLE
Place Details API: Documentation error

### ISSUE THREAD

**Issue by dqna64** [googlemaps/openapi-specification#242]
For the Place Details API documentation, under the PlaceOpeningHours section, the description for the `weekday_text` field is copied from the description of the `open_now` text field.

![image](https://user-images.githubusercontent.com/76837291/138563343-f62b2cca-fbfb-41e6-8a43-10be7f10b05b.png)

The existing example for the `weekday_text` field shows the following JSON entry:

```
...
"weekday_text":
            [
              "Monday: 9:00 AM – 5:00 PM",
              "Tuesday: 9:00 AM – 5:00 PM",
              "Wednesday: 9:00 AM – 5:00 PM",
              "Thursday: 9:00 AM – 5:00 PM",
              "Friday: 9:00 AM – 5:00 PM",
              "Saturday: Closed",
              "Sunday: Closed",
            ],
...
```

I suggest a new description for the `weekday_text` field as follows:

_An array of strings describing in human-readable text the weekly opening hours of the place._

This is just a suggestion. I'm not confident that it is accurate, and it could use some further clarification from someone who knows what the `weekday_text` field is supposed to be.

Thanks!

**Comment by jpoehnelt** [comment]
Thanks for reporting!
