### ISSUE TITLE
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Junfeizhao** [googlemaps/openapi-specification#256]
https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=cruise&location=-33.8670522%2C151.1957362&radius=1500&type=restaurant&key=yourkey

this api cannot use,I tried to use jsonp , but it didn't solve it .Is there any other way?

**Comment by jpoehnelt** [comment]
For browser environments, please use the [Google Maps Platform JavaScript API](https://developers.google.com/maps/documentation/javascript/overview) and [PlacesService](https://developers.google.com/maps/documentation/javascript/reference/places-service).

**Comment by jpoehnelt** [comment]
See this example: https://developers.google.com/maps/documentation/javascript/examples/place-search-pagination

**Comment by Junfeizhao** [comment]
I don't want to use the map method, because sometimes I want to call the method when the map is not loaded . Can't the API above be used? There are relevant examples on the website.
