### ISSUE TITLE
When i remove the infowindow on the marker ,there will appear a blue border on the map container. 

### ISSUE THREAD

**Issue by Junfeizhao** [googlemaps/openapi-specification#260]
When i remove the infowindow on the marker ,there will appear a blue border on the map container.  Is there any way to hide it? Thanks to you.

This is the div node of this blue border,but which has no class or id so i can not rewrite this style easily.
![图片](https://user-images.githubusercontent.com/47941990/144982475-9a78206c-83ef-4e3c-9cee-5434495ebab2.png)

**Comment by Junfeizhao** [comment]
![图片](https://user-images.githubusercontent.com/47941990/144983113-2f84b727-d756-4e45-b31b-e802297ecb1d.png)

**Comment by jpoehnelt** [comment]
Please file this in the correct location. https://developers.google.com/maps/documentation/javascript/support
