### ISSUE TITLE
optional parameters that aren't really optional for most use cases

### ISSUE THREAD

**Issue by annaswims** [googlemaps/openapi-specification#264]
#### Steps to reproduce
The   The [Places api Nearby Search documentation](https://developers.google.com/maps/documentation/places/web-service/search-nearby) says that `radius` is an optional parameter. However, when I make a request without the `radius` parameter I get a response with ` "status" : "INVALID_REQUEST"`

## should be valid:

[https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=cruise&location=-33.8670522%2C151.1957362&type=restaurant&key=YOUR_API_KEY](https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=cruise&location=-33.8670522%2C151.1957362&type=restaurant&key=YOUR_API_KEY)

```
{
   "html_attributions" : [],
   "results" : [],
   "status" : "INVALID_REQUEST"
}
```

## is valid and returns valid results
[https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=cruise&location=-33.8670522%2C151.1957362&type=restaurant&key=YOUR_API_KEY&radius=1000](https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=cruise&location=-33.8670522%2C151.1957362&type=restaurant&key=YOUR_API_KEY&radius=1000)

**Comment by jpoehnelt** [comment]
It's optional when `pagetoken` is provided and thus strictly speaking optional. Trying to keep to the strict definition here since the spec might be used to generate code. Sorry for these code smells!
