### ISSUE TITLE
Description parameter not found in response

### ISSUE THREAD

**Issue by hasnain37** [googlemaps/openapi-specification#381]
I want to fetch Google Business Profile description using API, currently using this API call https://developers.google.com/maps/documentation/places/web-service/details#place-details-example for fetching star ratings of Google my Business profiles but it does not have description parameter in its response result.

**Comment by wangela** [comment]
Are you looking for the new field `editorial_summary`, which is described here? https://developers.google.com/maps/documentation/places/web-service/details#Place-editorial_summary

The Public Issue Tracker corresponding to thie feature request is at https://issuetracker.google.com/issues/35827225.

Please re-open if this is not what you're looking for.

**Comment by hasnain37** [comment]
great thanks
