### ISSUE TITLE
Add "FUTURE_OPENING" to the business status enum

### ISSUE THREAD

**Issue by kavdev** [googlemaps/openapi-specification#402]
**Is your feature request related to a problem? Please describe.**
The current business_status enum is missing a value: FUTURE_OPENING

 **Describe the solution you'd like**
Add the value to the enum

**Comment by wangela** [comment]
Please follow [this issue](https://issuetracker.google.com/issues/249164721) in the public issue tracker to get updates about future openings in `business_status`.
