### ISSUE TITLE
Places: FindPlace API Bug - locationrestriction & locationbias not working

### ISSUE THREAD

**Issue by rnz269** [googlemaps/openapi-specification#406]
#### Steps to reproduce

  1. In Postman, trying to call findplacefromtext api, providing the input 'london' and specifying a location restriction of within 10000 meters of the coordinates of London, Ontario, Canada still returns the result London, England

#### Code example

```
  https://maps.googleapis.com/maps/api/place/findplacefromtext/json?key=<mykey>&inputtype=textquery&locationrestriction=circle:10000@42.9849233,-81.2452768&input=london&fields=place_id,name,formatted_address
```

#### Response
```
{
    "candidates": [
        {
            "formatted_address": "London, UK",
            "name": "London",
            "place_id": "ChIJdd4hrwug2EcRmSrV3Vo6llI"
        }
    ],
    "status": "OK"
}
```

Swapping locationrestriction with locationbias here, it also returns London, UK. I would somewhat expect locationbias to return London, Ontario, Canada, but I understand it depends on how strong the location bias is. 

However, I fully expect locationrestriction to return the 'london' that is within the location constraint provided. 

I also tried specifying a rectangle for locationrestriction, but that did not work either.

**Comment by tcpekin** [comment]
I am having the same issue with my query:

`https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=petisco&inputtype=textquery&fields=formatted_address%2Cname%2Crating%2Copening_hours%2Cgeometry%2Cplace_id&key=<key>&language=en&locationrestriction=circle%3A20000%4045.5152%2C-122.6784`

which should give a result in Portland, OR. Instead I'm getting results in the UK or Hamburg.

**Comment by wangela** [comment]
There is a [public issue tracker issue](https://issuetracker.google.com/issues/265054746) where support confirms that this parameter is unsupported.
