### ISSUE TITLE
Distance is not returning miles even if units=imperial 

### ISSUE THREAD

**Issue by kmmramos** [googlemaps/openapi-specification#412]
Currently, we have a method that gets the distance matrix from google distance api.

        public async Task<DistanceMatrix?> GetDistanceMatrix(List<string> rawDestinationAddress,
                                                                string rawOrigin,
                                                                string travelMode = "DRIVING",
                                                                string unitSystem = "imperial")
        {
            var destinationAddress = JsonSerializer.Serialize(rawDestinationAddress.Select(x => HttpUtility.UrlEncode(x)));

            string url = @$"api/distancematrix/json?origins={HttpUtility.UrlEncode(rawOrigin)}
                                                    &destinations={destinationAddress}
                                                    &travelMode={travelMode}
                                                    &units={unitSystem}
                                                    &key={Config.Key}";
            
            return await HttpClient.GetFromJsonAsync<DistanceMatrix>(url);
        }

Even though we're sending in units=imperial, we always get km in distance.text.

Note: We have tested it just using browser and in there, it returns miles but when we use it in our project, we always get km.

May we know what's the right value for units?

**Comment by wangela** [comment]
Please [file this as a bug](https://developers.google.com/maps/documentation/distance-matrix/support#bugs) in the Public Issue Tracker for the Distance Matrix API. This repo is for documentation of the API.
